FROM amazonlinux:2.0.20191016.0RUN yum install -y python38 && \
yum install -y python3-pip && \
yum install -y zip && \
yum clean allRUN python3.8 -m pip install --upgrade pip && \
python3.8 -m pip install virtualenv